version: "3.0.0"
services:
  "backend":
      build: "."
      ports:
      - "8000:8000"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis
